#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLeft,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     mArm,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*****************************
// All includes
//*****************************
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

//*****************************
// All defines
//*****************************
#define THRESHOLD 15

//*****************************
// All functions
//*****************************

// drive
void drive()
{
	//Move Forward or Backward
	motor[mLeft] = joystick.joy1_y1/2; //y1 controller moves motorD
	motor[mRight] = joystick.joy1_y2/2;
}

// Control Hand
//void grab()
//{
//	if(joy1Btn(1))
//	{
//		// Joy1-Button1 is pressed
//		// Turn Motor A On at full power
//		servo[ring] = 100;
//	}
//	else if(joy1Btn(2))
//	{
//		// If Joy1-Button1 is NOT pressed:
//		// Turn Motor A Off
//		servo[ring] = 0;
//	}
//}

// init
void initializeRobot()
{
	return;
}

void arm()
{
	//Arm up
	if(joy1Btn(6)) {
		motor[mArm] = 30;
	}
	//Arm down
	else if(joy1Btn(8)) {
		motor[mArm] = -30;
	}
	//No arm movement
	else {
		motor[mArm] = 0;
	}
}
//*****************************
// Main
//*****************************
task main()
{
	initializeRobot();

	// waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		//retrieves data from the joystick
		getJoystickSettings(joystick);

		// drive robot
		drive();

		// use hand
		//grab();
		arm();
	}
}
